version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directories:
      - /
      - packages/web-features
      - packages/compute-baseline
      - gh-pages
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        # Data packages are excluded from cooldowns, since we want those more urgently
        - "@mdn/browser-compat-data"
        - "caniuse-lite"
        - "web-specs"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      # Groups are applied in order, so narrowest groups go first
      types-node:
        patterns:
          - "@types/node"
      typescript:
        patterns:
          - "typescript"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          # Data packages are excluded from all groups, to get their own PRs
          - "@mdn/browser-compat-data"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          # Data packages are excluded from all groups, to get their own PRs
          - "@mdn/browser-compat-data"
          - "web-specs"
          - "caniuse-lite"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
