name: Prepare web-features release

on:
  workflow_dispatch:
    inputs:
      semverLevel:
        description: "Bump to semver level"
        required: true
        type: choice
        default: "minor"
        options:
          - patch
          - minor
          - major

jobs:
  open_pr:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - name: ./scripts/release.ts init
        run: npx tsx ./scripts/release.ts init --target-repo=$REPO --reviewers=$ACTOR $SEMVER_LEVEL
        env:
          ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SEMVER_LEVEL: ${{ inputs.semverLevel }}
